maj fichiers xdebug et editor.config
WildCodeSchool/2022-09-php-remote-p2-where-is-my-band pull request #6
Opened 2022-10-27 09:25 UTC by marinevlrg

ajout page accueil et débug avec jf

2022-10-27 09:48 UTC, Hugodvd1 approved these changes

2022-10-28 05:58 UTC, jfm-wcs requested changes
pour moi c'est tout bon, juste une petite précision css qui ne devrait pas prendre plus de 2 minutes 😉

2022-10-28 05:58 UTC, jfm-wcs commented on public/assets/css/_index.css
> +    background: rgba(186, 24, 27, 0.9);
tu ne devrais pas utiliser le nom d'une classe bootstrap pour faire ça mais un nom perso.
Imagine, si vous décidiez finalement de mettre une `col-md-6` juste parce que c'est un meilleur point de rupture ? 🥸.
de plus `background-color` et `background` sont en conflit je pense 😉

2022-10-28 08:35 UTC, jfm-wcs approved these changes

2022-10-28 08:35 UTC, merged